import json
import yt_dlp
import os
import re
import tempfile
from flask import Flask, request, jsonify, render_template_string

# Initialize Flask app
app = Flask(__name__)

# Default path for local cookie storage in workspace
DEFAULT_WORKSPACE_COOKIE_PATH = os.path.join(os.getcwd(), "cookies.txt")

def parse_pasted_cookies(cookie_text):
    """
    Parses various cookie formats (Netscape, JSON, or standard Cookie header string)
    and returns a clean Netscape-format string.
    """
    cookie_text = cookie_text.strip()
    if not cookie_text:
        return ""

    # Case 1: Already Netscape format
    if "# Netscape HTTP Cookie File" in cookie_text or re.search(r"^\S+\t+(?:TRUE|FALSE)\t+\S+\t+(?:TRUE|FALSE)", cookie_text, re.MULTILINE):
        if "# Netscape HTTP Cookie File" not in cookie_text:
            return "# Netscape HTTP Cookie File\n" + cookie_text
        return cookie_text

    # Case 2: JSON Format
    try:
        data = json.loads(cookie_text)
        if isinstance(data, list):
            netscape_lines = ["# Netscape HTTP Cookie File", "# Generated by Cookie Helper"]
            for item in data:
                domain = item.get("domain", "")
                # Netscape format requires domain to start with . if it covers subdomains
                include_sub = "TRUE" if domain.startswith(".") else "FALSE"
                path = item.get("path", "/")
                secure = "TRUE" if item.get("secure", False) else "FALSE"
                # Expiration
                expiry = item.get("expirationDate") or item.get("expiry")
                if expiry is None:
                    expiry = 0
                expiry = int(expiry)
                name = item.get("name", "")
                value = item.get("value", "")
                
                if domain and name:
                    netscape_lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
            return "\n".join(netscape_lines)
    except Exception:
        pass

    # Case 3: Key-Value / Cookie Header Format (e.g. "name1=value1; name2=value2")
    # Clean standard Header label if present
    if cookie_text.lower().startswith("cookie:"):
        cookie_text = cookie_text[7:].strip()
    
    parts = cookie_text.split(";")
    netscape_lines = ["# Netscape HTTP Cookie File", "# Generated from Cookie Header", ".hotstar.com\tTRUE\t/\tTRUE\t2082758400"]
    has_cookies = False
    for part in parts:
        if "=" in part:
            name, value = part.strip().split("=", 1)
            netscape_lines.append(f".hotstar.com\tTRUE\t/\tTRUE\t2082758400\t{name}\t{value}")
            has_cookies = True
            
    if has_cookies:
        return "\n".join(netscape_lines)

    return ""

def extract_cookies_with_playwright(url, headless=True):
    """
    Spins up a browser session using Playwright to visit the target URL,
    stealthily extracts session cookies and intercepts network traffic for streaming manifests.
    Supports headless and interactive (non-headless) login sessions.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        raise RuntimeError(
            "Playwright package is not installed.\n"
            "To use automated browser extraction, make sure to install it in your environment:\n"
            "  pip install playwright\n"
            "  playwright install chromium"
        )

    mode_str = "headless" if headless else "INTERACTIVE POPUP (non-headless)"
    print(f"[PLAYWRIGHT] Launching browser ({mode_str}) to retrieve session cookies and sniff streams for: {url}")
    
    sniffed_streams = []

    try:
        with sync_playwright() as p:
            try:
                browser = p.chromium.launch(
                    headless=headless,
                    args=["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"]
                )
            except Exception as launch_err:
                raise RuntimeError(
                    f"Failed to launch Chromium browser: {str(launch_err)}\n"
                    "This usually means chromium system libraries are missing in this environment.\n"
                    "Please install them using:\n"
                    "  playwright install chromium"
                )

            # Mask browser footprint with user agent
            context = browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
                viewport={"width": 1280, "height": 720}
            )
            page = context.new_page()
            
            # Setup network sniffer to capture live streams and their exact headers
            def handle_request(req):
                req_url = req.url
                url_lower = req_url.lower()
                if ".m3u8" in url_lower or ".mpd" in url_lower or "manifest" in url_lower or "/master" in url_lower or "/playlist" in url_lower:
                    if not any(x in url_lower for x in ["googletagservices", "google-analytics", "facebook", "segment.io", "hotjar"]):
                        try:
                            headers_dict = dict(req.headers)
                            if not any(s['url'] == req_url for s in sniffed_streams):
                                stream_type = "HLS (m3u8)" if ".m3u8" in url_lower else "DASH (mpd)"
                                if "manifest" in url_lower and "dash" in url_lower:
                                    stream_type = "DASH (mpd)"
                                sniffed_streams.append({
                                    "url": req_url,
                                    "headers": headers_dict,
                                    "type": stream_type
                                })
                                print(f"[SNIFFER] Captured active stream ({stream_type}): {req_url[:80]}...")
                        except Exception as sniffer_err:
                            pass

            page.on("request", handle_request)
            
            print(f"[PLAYWRIGHT] Navigating to URL: {url}...")
            page.goto(url, wait_until="commit", timeout=35000)
            
            if not headless:
                print("[PLAYWRIGHT] INTERACTIVE LOGIN INSTRUCTIONS:")
                print("1. A browser window has opened on your computer.")
                print("2. Log into your Hotstar account (or let page load completely).")
                print("3. Once logged in, either close the browser window or wait 90 seconds.")
                # Give user plenty of time to log in interactively (up to 90 seconds)
                for i in range(45):
                    page.wait_for_timeout(2000)
                    try:
                        if page.is_closed():
                            print("[PLAYWRIGHT] User closed the window. Proceeding to save cookies...")
                            break
                    except Exception:
                        break
            else:
                # Headless delay
                page.wait_for_timeout(8000)
            
            try:
                cookies = context.cookies()
            except Exception:
                cookies = []
                
            try:
                browser.close()
            except Exception:
                pass
            
            # Construct Netscape cookie format
            netscape_lines = ["# Netscape HTTP Cookie File", "# Automatically harvested by Playwright Stealth Engine"]
            for c in cookies:
                domain = c.get("domain", "")
                include_sub = "TRUE" if domain.startswith(".") else "FALSE"
                path = c.get("path", "/")
                secure = "TRUE" if c.get("secure", False) else "FALSE"
                expiry = int(c.get("expires", 2082758400))
                if expiry < 0:
                    expiry = 2082758400
                name = c.get("name", "")
                value = c.get("value", "")
                
                if domain and name:
                    netscape_lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
            
            print(f"[PLAYWRIGHT] Successfully extracted {len(cookies)} cookies and sniffed {len(sniffed_streams)} stream manifests.")
            return "\n".join(netscape_lines), sniffed_streams
    except Exception as e:
        raise RuntimeError(f"Playwright Extraction Error: {str(e)}")

def fetch_platform_metadata(url, cookie_source="file", custom_file_path=None, pasted_cookie_content=None, browser_name="chrome", playwright_headless=True):
    ydl_opts = {
        'skip_download': True,
        'extract_flat': False,
        'force_generic_extractor': False,
        'nocheckcertificate': True, 
        'prefer_insecure': True,
    }

    temp_cookie_file = None
    sniffed_streams = []

    try:
        # Configure Cookies based on source selection
        if cookie_source == "pasted" and pasted_cookie_content:
            netscape_cookies = parse_pasted_cookies(pasted_cookie_content)
            if netscape_cookies:
                # Create a temporary file to hold the parsed Netscape cookies
                fd, temp_path = tempfile.mkstemp(suffix=".txt", prefix="cookies_")
                with os.fdopen(fd, 'w', encoding='utf-8') as f:
                    f.write(netscape_cookies)
                temp_cookie_file = temp_path
                ydl_opts['cookiefile'] = temp_cookie_file
                print(f"[INFO] Using pasted cookies saved to temporary path: {temp_cookie_file}")
            else:
                raise ValueError("Could not parse pasted cookies. Ensure they are in Netscape, JSON, or Cookie Header format.")
        
        elif cookie_source == "playwright_auto":
            print(f"[INFO] Running automated session orchestration using Playwright on: {url} (headless={playwright_headless})")
            playwright_cookies, sniffed_streams = extract_cookies_with_playwright(url, headless=playwright_headless)
            
            # Save harvested cookies to temporary file
            fd, temp_path = tempfile.mkstemp(suffix=".txt", prefix="cookies_pw_")
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                f.write(playwright_cookies)
            temp_cookie_file = temp_path
            ydl_opts['cookiefile'] = temp_cookie_file
            print(f"[INFO] Using Playwright harvested cookies: {temp_cookie_file}")

        elif cookie_source == "browser":
            print(f"[INFO] Loading active cookies directly from browser: {browser_name}")
            ydl_opts['cookiesfrombrowser'] = (browser_name,)
            
        elif cookie_source == "none":
            print("[INFO] Running without any cookies. Only free public streams will work.")
            
        else: # Default to "file"
            file_to_use = custom_file_path if custom_file_path else DEFAULT_WORKSPACE_COOKIE_PATH
            if os.path.exists(file_to_use):
                print(f"[INFO] Loading cookies from file: {file_to_use}")
                ydl_opts['cookiefile'] = file_to_use
            else:
                print(f"[WARNING] Cookie file not found at {file_to_use}. Attempting direct browser extraction: {browser_name}")
                ydl_opts['cookiesfrombrowser'] = (browser_name,)

        # Extract info using yt-dlp
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                print(f"[INFO] Extracting data from: {url}")
                info_dict = ydl.extract_info(url, download=False)
                
                structured_data = {
                    "Title": info_dict.get('title'),
                    "Content_ID": info_dict.get('id'),
                    "Series_Name": info_dict.get('series'),
                    "Episode_Number": info_dict.get('episode_number'),
                    "Release_Date": info_dict.get('upload_date'),
                    "Duration_Seconds": info_dict.get('duration'),
                    "Description": info_dict.get('description'),
                    "Thumbnails": [t.get('url') for t in info_dict.get('thumbnails', []) if t.get('url')],
                    "Sniffed_Streams": sniffed_streams
                }
                
                subtitles = info_dict.get('subtitles', {})
                structured_data["Available_Subtitles"] = list(subtitles.keys())
                
                formats_list = []
                for fmt in info_dict.get('formats', []):
                    formats_list.append({
                        "Format_ID": fmt.get('format_id'),
                        "Resolution": f"{fmt.get('width')}x{fmt.get('height')}" if fmt.get('width') else "Audio-Only",
                        "Video_Codec": fmt.get('vcodec'),
                        "Audio_Codec": fmt.get('acodec'),
                        "FPS": fmt.get('fps'),
                        "Bitrate_kbps": int(fmt.get('tbr')) if fmt.get('tbr') else None,
                        "Container_Ext": fmt.get('ext'),
                        "Stream_Manifest_URL": fmt.get('url')  
                    })
                
                structured_data["Available_Formats"] = formats_list
                return structured_data
        except Exception as ydl_err:
            # If yt-dlp fails but we have sniffed streams, let's gracefully return them!
            if sniffed_streams:
                print(f"[WARNING] yt-dlp failed but sniffed_streams are available: {str(ydl_err)}")
                formats_list = []
                for idx, s in enumerate(sniffed_streams):
                    formats_list.append({
                        "Format_ID": f"sniffed-{idx + 1}",
                        "Resolution": f"Stream {idx + 1} ({s['type']})",
                        "Video_Codec": "H.264 / AAC",
                        "Audio_Codec": "Dynamic",
                        "FPS": None,
                        "Bitrate_kbps": None,
                        "Container_Ext": "m3u8" if "m3u8" in s["type"].lower() else "mpd",
                        "Stream_Manifest_URL": s["url"],
                        "Headers": s["headers"]
                    })
                return {
                    "Title": "Captured Stream (LJ Downloader Mode)",
                    "Content_ID": "sniffed_fallback",
                    "Series_Name": "Automated Network Interceptor",
                    "Episode_Number": None,
                    "Release_Date": "Live Captured",
                    "Duration_Seconds": None,
                    "Description": "yt-dlp is unable to read metadata directly due to DRM or login walls. However, the Playwright engine successfully intercepted the active web-player media URL and session authorization headers directly from the network pipeline.",
                    "Thumbnails": [],
                    "Available_Subtitles": [],
                    "Available_Formats": formats_list,
                    "Sniffed_Streams": sniffed_streams
                }
            else:
                raise ydl_err

    except Exception as e:
        error_msg = str(e)
        troubleshooting = ""
        if "only available for registered users" in error_msg:
            troubleshooting = (
                "\n\n[COOKIES EXPIRED OR INVALID]\n"
                "Your current Hotstar session cookies have expired or are missing standard registration credentials.\n"
                "To resolve this in the interface:\n"
                "1. Log into Hotstar in your browser.\n"
                "2. Copy the cookies (using a Cookie Editor extension as Netscape/JSON, or directly copy the 'Cookie' Request Header).\n"
                "3. Paste them into the Cookie Helper box below and try again."
            )
        return {"error": f"Extraction Failed: {error_msg}{troubleshooting}"}
        
    finally:
        # Clean up temporary cookie file if created
        if temp_cookie_file and os.path.exists(temp_cookie_file):
            try:
                os.remove(temp_cookie_file)
            except Exception:
                pass

# ================= FLASK UI TEMPLATE =================
HTML_TEMPLATE = r"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotstar Metadata Extractor & Cookie Fixer</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Space Grotesk', sans-serif;
            background-color: #0b0f19;
            color: #f3f4f6;
        }
        .mono {
            font-family: 'JetBrains Mono', monospace;
        }
    </style>
</head>
<body class="min-h-screen py-10 px-4 sm:px-6 lg:px-8">
    <div id="app" class="max-w-6xl mx-auto">
        <!-- Header -->
        <header class="text-center mb-10 border-b border-gray-800 pb-8">
            <h1 class="text-4xl font-bold tracking-tight bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-500 bg-clip-text text-transparent">
                Hotstar Extractor & Cookie Engine
            </h1>
            <p class="mt-3 text-gray-400 text-lg max-w-2xl mx-auto">
                Extract metadata, stream manifests, and subtitle URLs. Troubleshoot, format, and fix expired session cookies.
            </p>
        </header>

        <!-- Main Workspace Grid -->
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
            
            <!-- Left Side: Config & Form -->
            <div class="lg:col-span-5 space-y-6">
                <!-- extraction card -->
                <div class="bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-xl">
                    <h2 class="text-xl font-semibold mb-4 flex items-center gap-2">
                        <span class="p-1.5 bg-blue-500/10 text-blue-400 rounded-lg">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path></svg>
                        </span>
                        Extractor Controls
                    </h2>
                    
                    <form id="extractForm" class="space-y-4">
                        <!-- Target URL -->
                        <div>
                            <label class="block text-sm font-medium text-gray-300 mb-1">Target Video URL</label>
                            <input type="url" id="targetUrl" required 
                                   placeholder="https://www.hotstar.com/..." 
                                   value="https://www.hotstar.com/in/shows/dr-aarambhi/1271522330/aarambhi-learns-a-shocking-truth/1641024438/watch"
                                   class="w-full bg-gray-950 border border-gray-800 rounded-xl px-4 py-3 text-gray-100 placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500 transition">
                        </div>

                        <!-- Cookie Extraction Method -->
                        <div>
                            <label class="block text-sm font-medium text-gray-300 mb-1">Session Cookie Method</label>
                            <select id="cookieSource" class="w-full bg-gray-950 border border-gray-800 rounded-xl px-4 py-3 text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 transition">
                                <option value="playwright_auto">Playwright Automated (Stealth Session Extraction)</option>
                                <option value="pasted">Paste Live Cookies / Raw Headers (Recommended)</option>
                                <option value="file">Local Cookies File (cookies.txt)</option>
                                <option value="browser">Direct Browser Extraction (Local PC Only)</option>
                                <option value="none">No Cookies (Only works for completely free videos)</option>
                            </select>
                        </div>

                        <!-- Playwright Mode Selection (Conditional) -->
                        <div id="playwrightSection" class="bg-gray-950/40 border border-gray-800 rounded-xl p-4 space-y-3">
                            <div class="flex items-center gap-2">
                                <input type="checkbox" id="playwrightHeadless" checked class="w-4 h-4 text-blue-600 bg-gray-900 border-gray-700 rounded focus:ring-blue-500 accent-blue-600 cursor-pointer">
                                <label for="playwrightHeadless" class="text-xs font-semibold text-gray-300 cursor-pointer select-none">
                                    Headless Mode (Silent Run)
                                </label>
                            </div>
                            <p class="text-[11px] text-gray-500 leading-relaxed">
                                <strong>Interactive Login Bypass:</strong> If a video requires registration, uncheck this box. When you click Fetch, a browser window will pop up on your computer. Simply complete the OTP/mobile login on Hotstar, then close the window or wait! The script will automatically capture your premium session cookies.
                            </p>
                        </div>

                        <!-- Browser Selection (Conditional) -->
                        <div id="browserSection" class="hidden">
                            <label class="block text-sm font-medium text-gray-300 mb-1">Select Browser</label>
                            <select id="browserName" class="w-full bg-gray-950 border border-gray-800 rounded-xl px-4 py-3 text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 transition">
                                <option value="chrome">Google Chrome</option>
                                <option value="edge">Microsoft Edge</option>
                                <option value="firefox">Mozilla Firefox</option>
                                <option value="brave">Brave Browser</option>
                            </select>
                        </div>

                        <!-- Cookie File Path Selection (Conditional) -->
                        <div id="filePathSection" class="hidden">
                            <label class="block text-sm font-medium text-gray-300 mb-1">Cookies File Absolute Path</label>
                            <input type="text" id="cookieFilePath" 
                                   placeholder="C:\Users\hp\Music\shorts\cookies.txt"
                                   value="C:\Users\hp\Music\shorts\cookies.txt"
                                   class="w-full bg-gray-950 border border-gray-800 rounded-xl px-4 py-3 text-gray-100 placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500 transition">
                        </div>

                        <!-- Submit Button -->
                        <button type="submit" id="submitBtn" class="w-full mt-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-semibold py-3.5 px-4 rounded-xl shadow-lg hover:shadow-indigo-500/20 active:scale-[0.98] transition flex items-center justify-center gap-2">
                            <span id="btnText">Fetch Platform Architecture</span>
                            <div id="spinner" class="hidden w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                        </button>
                    </form>
                </div>

                <!-- Cookie Helper Box -->
                <div class="bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-xl">
                    <h2 class="text-xl font-semibold mb-2 flex items-center gap-2">
                        <span class="p-1.5 bg-indigo-500/10 text-indigo-400 rounded-lg">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path></svg>
                        </span>
                        Cookie Fixer & Parser
                    </h2>
                    <p class="text-sm text-gray-400 mb-4">
                        Paste cookies directly from a logged-in Hotstar window. Supports Netscape, JSON, or standard Cookie Headers.
                    </p>
                    
                    <textarea id="pastedCookies" rows="6" 
                              placeholder="# Netscape HTTP Cookie File&#10;OR JSON: [{'name': 'sub_status', 'value': 'premium', ...}]&#10;OR RAW HEADER: sub_status=premium; identity=..."
                              class="w-full bg-gray-950 border border-gray-800 rounded-xl p-3 text-sm mono text-gray-200 placeholder-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition mb-3"></textarea>

                    <div class="flex gap-2">
                        <button id="saveCookiesBtn" class="flex-1 bg-gray-800 hover:bg-gray-700 text-sm text-gray-200 font-medium py-2 px-3 rounded-lg border border-gray-700 transition active:scale-95">
                            Save Locally (cookies.txt)
                        </button>
                        <button id="clearCookiesBtn" class="bg-red-950/20 hover:bg-red-950/40 text-sm text-red-400 font-medium py-2 px-3 rounded-lg border border-red-900/30 transition active:scale-95">
                            Clear
                        </button>
                    </div>
                    <div id="cookieStatus" class="hidden mt-3 p-3 rounded-xl text-xs font-medium border"></div>
                </div>
            </div>

            <!-- Right Side: Display Output/Results -->
            <div class="lg:col-span-7 space-y-6">
                <!-- Welcome/Placeholder Panel -->
                <div id="placeholderPanel" class="bg-gray-900/40 border border-gray-800/80 rounded-2xl p-12 text-center h-full flex flex-col items-center justify-center min-h-[400px]">
                    <div class="w-16 h-16 bg-gray-900 border border-gray-800 rounded-2xl flex items-center justify-center text-gray-400 mb-4 animate-pulse">
                        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"></path></svg>
                    </div>
                    <h3 class="text-xl font-semibold text-gray-300">Ready to Analyze</h3>
                    <p class="text-gray-500 max-w-sm mt-2 text-sm leading-relaxed">
                        Configure your cookie validation strategy and supply a target URL to parse structural stream pipelines.
                    </p>
                </div>

                <!-- Error Panel -->
                <div id="errorPanel" class="hidden bg-red-950/20 border border-red-900/40 rounded-2xl p-6 space-y-4">
                    <div class="flex items-start gap-3">
                        <span class="p-1.5 bg-red-500/20 text-red-400 rounded-lg mt-0.5">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                        </span>
                        <div>
                            <h3 class="text-lg font-semibold text-red-400">Extraction Error</h3>
                            <div id="errorText" class="mt-2 text-sm text-red-300 leading-relaxed whitespace-pre-line mono text-xs p-3 bg-black/40 rounded-xl border border-red-950/50"></div>
                        </div>
                    </div>
                </div>

                <!-- Result Panel -->
                <div id="resultPanel" class="hidden space-y-6">
                    
                    <!-- Basic Metadata Card -->
                    <div class="bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-xl">
                        <div class="flex flex-col sm:flex-row justify-between items-start gap-4">
                            <div>
                                <span class="px-2.5 py-1 bg-blue-500/10 text-blue-400 text-xs font-semibold rounded-full uppercase tracking-wider" id="resId"></span>
                                <h2 class="text-2xl font-bold mt-2" id="resTitle"></h2>
                                <p class="text-gray-400 text-sm mt-1" id="resSeriesInfo"></p>
                            </div>
                            <div class="text-right text-sm">
                                <p class="text-gray-400">Duration</p>
                                <p class="font-semibold text-gray-200 text-lg" id="resDuration"></p>
                            </div>
                        </div>
                        
                        <p class="mt-4 text-gray-400 text-sm leading-relaxed" id="resDescription"></p>
                        
                        <!-- Thumbnails Grid -->
                        <div class="mt-6">
                            <h4 class="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Primary Thumbnail</h4>
                            <div class="aspect-video w-full max-w-md bg-gray-950 rounded-xl overflow-hidden border border-gray-800">
                                <img id="resThumbnail" src="" alt="Thumbnail" class="w-full h-full object-cover">
                            </div>
                        </div>
                    </div>

                    <!-- Available Formats Card -->
                    <div class="bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-xl overflow-hidden">
                        <h3 class="text-lg font-semibold mb-4 flex items-center gap-2">
                            <svg class="w-5 h-5 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                            Available Adaptive Streams
                        </h3>
                        
                        <div class="overflow-x-auto">
                            <table class="w-full text-left border-collapse text-xs">
                                <thead>
                                    <tr class="border-b border-gray-800 text-gray-400">
                                        <th class="py-3 px-4">Format ID</th>
                                        <th class="py-3 px-4">Resolution</th>
                                        <th class="py-3 px-4">Video Codec</th>
                                        <th class="py-3 px-4">Audio Codec</th>
                                        <th class="py-3 px-4 text-right">Bitrate (kbps)</th>
                                        <th class="py-3 px-4 text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody id="formatsTableBody" class="divide-y divide-gray-800/40 text-gray-300">
                                    <!-- Dynamic rows -->
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>

    <script>
        const cookieSourceSelect = document.getElementById('cookieSource');
        const browserSection = document.getElementById('browserSection');
        const filePathSection = document.getElementById('filePathSection');
        const playwrightSection = document.getElementById('playwrightSection');
        const extractForm = document.getElementById('extractForm');
        const submitBtn = document.getElementById('submitBtn');
        const spinner = document.getElementById('spinner');
        const btnText = document.getElementById('btnText');
        
        const placeholderPanel = document.getElementById('placeholderPanel');
        const errorPanel = document.getElementById('errorPanel');
        const errorText = document.getElementById('errorText');
        const resultPanel = document.getElementById('resultPanel');
        
        // Results fields
        const resId = document.getElementById('resId');
        const resTitle = document.getElementById('resTitle');
        const resSeriesInfo = document.getElementById('resSeriesInfo');
        const resDuration = document.getElementById('resDuration');
        const resDescription = document.getElementById('resDescription');
        const resThumbnail = document.getElementById('resThumbnail');
        const formatsTableBody = document.getElementById('formatsTableBody');

        const saveCookiesBtn = document.getElementById('saveCookiesBtn');
        const clearCookiesBtn = document.getElementById('clearCookiesBtn');
        const pastedCookies = document.getElementById('pastedCookies');
        const cookieStatus = document.getElementById('cookieStatus');

        // Toggle form fields based on selection
        cookieSourceSelect.addEventListener('change', (e) => {
            const val = e.target.value;
            if (val === 'browser') {
                browserSection.classList.remove('hidden');
                filePathSection.classList.add('hidden');
                playwrightSection.classList.add('hidden');
            } else if (val === 'file') {
                browserSection.classList.add('hidden');
                filePathSection.classList.remove('hidden');
                playwrightSection.classList.add('hidden');
            } else if (val === 'playwright_auto') {
                browserSection.classList.add('hidden');
                filePathSection.classList.add('hidden');
                playwrightSection.classList.remove('hidden');
            } else {
                browserSection.classList.add('hidden');
                filePathSection.classList.add('hidden');
                playwrightSection.classList.add('hidden');
            }
        });

        // Initialize state
        if (cookieSourceSelect.value === 'playwright_auto') {
            playwrightSection.classList.remove('hidden');
        } else {
            playwrightSection.classList.add('hidden');
        }

        // Parse format seconds
        function formatDuration(sec) {
            if (!sec) return 'N/A';
            const h = Math.floor(sec / 3600);
            const m = Math.floor((sec % 3600) / 60);
            const s = Math.floor(sec % 60);
            return h > 0 ? `${h}h ${m}m ${s}s` : `${m}m ${s}s`;
        }

        // Handle Metadata Extraction Form Submit
        extractForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            
            // Set loading state
            submitBtn.disabled = true;
            spinner.classList.remove('hidden');
            btnText.textContent = "Analyzing Pipeline...";
            
            errorPanel.classList.add('hidden');
            resultPanel.classList.add('hidden');
            placeholderPanel.classList.remove('hidden');

            const payload = {
                url: document.getElementById('targetUrl').value,
                cookie_source: cookieSourceSelect.value,
                custom_file_path: document.getElementById('cookieFilePath').value,
                pasted_cookie_content: pastedCookies.value,
                browser_name: document.getElementById('browserName').value,
                playwright_headless: document.getElementById('playwrightHeadless').checked
            };

            try {
                const response = await fetch('/api/fetch', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload)
                });
                const data = await response.json();

                if (data.error) {
                    errorText.textContent = data.error;
                    errorPanel.classList.remove('hidden');
                    placeholderPanel.classList.add('hidden');
                } else {
                    // Populate result UI
                    resId.textContent = `ID: ${data.Content_ID || 'Unknown'}`;
                    resTitle.textContent = data.Title || 'N/A';
                    
                    let series = data.Series_Name ? `Series: ${data.Series_Name}` : '';
                    let episode = data.Episode_Number ? ` | Episode: ${data.Episode_Number}` : '';
                    resSeriesInfo.textContent = (series + episode) || 'Standalone Clip / Stream';
                    
                    resDuration.textContent = formatDuration(data.Duration_Seconds);
                    resDescription.textContent = data.Description || 'No description provided.';
                    
                    if (data.Thumbnails && data.Thumbnails.length > 0) {
                        resThumbnail.src = data.Thumbnails[0];
                    } else {
                        resThumbnail.src = '';
                    }

                    // Formats table
                    formatsTableBody.innerHTML = '';
                    if (data.Available_Formats && data.Available_Formats.length > 0) {
                        data.Available_Formats.forEach(fmt => {
                            const tr = document.createElement('tr');
                            tr.className = "hover:bg-gray-800/20 transition";
                            
                            let actionHtml = `
                                <button onclick="copyToClipboard('${fmt.Stream_Manifest_URL}')" class="px-2 py-1 bg-indigo-950/40 text-indigo-300 border border-indigo-900/40 rounded hover:bg-indigo-900/60 transition active:scale-95 text-xs font-semibold">
                                    Copy URL
                                </button>
                            `;
                            
                            // If stream headers are sniffed, render custom action buttons (LJ Downloader Style)
                            if (fmt.Headers) {
                                const encodedHeaders = btoa(unescape(encodeURIComponent(JSON.stringify(fmt.Headers))));
                                actionHtml += `
                                    <button onclick="copyHeaders('${encodedHeaders}')" class="px-2 py-1 bg-emerald-950/40 text-emerald-300 border border-emerald-900/40 rounded hover:bg-emerald-900/60 transition active:scale-95 text-xs font-semibold" title="Copy Request Headers & Cookie Info">
                                        Copy Headers
                                    </button>
                                `;
                            }
                            
                            tr.innerHTML = `
                                <td class="py-3 px-4 font-semibold text-blue-400 mono">${fmt.Format_ID || 'N/A'}</td>
                                <td class="py-3 px-4 font-medium">${fmt.Resolution}</td>
                                <td class="py-3 px-4 text-gray-400 mono">${fmt.Video_Codec || 'N/A'}</td>
                                <td class="py-3 px-4 text-gray-400 mono">${fmt.Audio_Codec || 'N/A'}</td>
                                <td class="py-3 px-4 text-right font-medium">${fmt.Bitrate_kbps ? fmt.Bitrate_kbps.toLocaleString() : 'N/A'}</td>
                                <td class="py-3 px-4 text-center">
                                    <div class="flex items-center justify-center gap-2">
                                        ${actionHtml}
                                    </div>
                                </td>
                            `;
                            formatsTableBody.appendChild(tr);
                        });
                    } else {
                        formatsTableBody.innerHTML = `<tr><td colspan="6" class="text-center py-6 text-gray-500">No stream formats found. Verify your Hotstar authorization.</td></tr>`;
                    }

                    placeholderPanel.classList.add('hidden');
                    resultPanel.classList.remove('hidden');
                }
            } catch (err) {
                errorText.textContent = `Client Request Error: ${err.message}`;
                errorPanel.classList.remove('hidden');
                placeholderPanel.classList.add('hidden');
            } finally {
                submitBtn.disabled = false;
                spinner.classList.add('hidden');
                btnText.textContent = "Fetch Platform Architecture";
            }
        });

        // Save Cookies to local Workspace
        saveCookiesBtn.addEventListener('click', async () => {
            const cookiesVal = pastedCookies.value.strip ? pastedCookies.value.strip() : pastedCookies.value.trim();
            if (!cookiesVal) {
                showCookieStatus("Please paste some valid cookie content first.", "error");
                return;
            }

            try {
                const response = await fetch('/api/save_cookies', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ cookies: cookiesVal })
                });
                const data = await response.json();
                if (data.success) {
                    showCookieStatus("Successfully saved cookies to local cookies.txt file!", "success");
                } else {
                    showCookieStatus(`Failed to save cookies: ${data.error}`, "error");
                }
            } catch (err) {
                showCookieStatus(`Server error: ${err.message}`, "error");
            }
        });

        clearCookiesBtn.addEventListener('click', () => {
            pastedCookies.value = '';
            cookieStatus.classList.add('hidden');
        });

        function showCookieStatus(message, type) {
            cookieStatus.textContent = message;
            cookieStatus.classList.remove('hidden', 'bg-green-950/30', 'text-green-400', 'border-green-900/30', 'bg-red-950/30', 'text-red-400', 'border-red-900/30');
            if (type === 'success') {
                cookieStatus.classList.add('bg-green-950/30', 'text-green-400', 'border-green-900/30');
            } else {
                cookieStatus.classList.add('bg-red-950/30', 'text-red-400', 'border-red-900/30');
            }
        }

        function copyToClipboard(text) {
            if (!text || text === 'undefined') {
                alert('No manifest URL available for copying.');
                return;
            }
            navigator.clipboard.writeText(text).then(() => {
                alert('Copied stream manifest URL to clipboard!');
            }).catch(err => {
                console.error('Failed to copy: ', err);
            });
        }

        function copyHeaders(base64Headers) {
            try {
                const headers = JSON.parse(decodeURIComponent(escape(atob(base64Headers))));
                let formatted = "";
                for (const [k, v] of Object.entries(headers)) {
                    formatted += `${k}: ${v}\n`;
                }
                navigator.clipboard.writeText(formatted).then(() => {
                    alert('Copied active request headers & authorization context to clipboard! Use these with your download manager.');
                }).catch(err => {
                    console.error('Failed to copy headers: ', err);
                });
            } catch (err) {
                alert('Failed to parse headers: ' + err.message);
            }
        }
    </script>
</body>
</html>
"""

# ================= FLASK CONTROLLERS =================

@app.route('/')
def home():
    return render_template_string(HTML_TEMPLATE)

@app.route('/api/fetch', methods=['POST'])
def api_fetch():
    data = request.get_json() or {}
    url = data.get('url')
    cookie_source = data.get('cookie_source', 'pasted')
    custom_file_path = data.get('custom_file_path')
    pasted_cookie_content = data.get('pasted_cookie_content')
    browser_name = data.get('browser_name', 'chrome')
    playwright_headless = data.get('playwright_headless', True)

    if not url:
        return jsonify({"error": "Target video URL is required."}), 400

    result = fetch_platform_metadata(
        url=url,
        cookie_source=cookie_source,
        custom_file_path=custom_file_path,
        pasted_cookie_content=pasted_cookie_content,
        browser_name=browser_name,
        playwright_headless=playwright_headless
    )
    return jsonify(result)

@app.route('/api/save_cookies', methods=['POST'])
def api_save_cookies():
    data = request.get_json() or {}
    pasted_text = data.get('cookies', '').strip()
    
    if not pasted_text:
        return jsonify({"error": "No cookies provided."}), 400

    netscape_content = parse_pasted_cookies(pasted_text)
    if not netscape_content:
        return jsonify({"error": "Could not parse standard cookie structure. Please ensure Netscape, JSON, or standard Cookie Headers are provided."}), 400

    try:
        # Write to local cookies.txt in workspace
        with open(DEFAULT_WORKSPACE_COOKIE_PATH, "w", encoding="utf-8") as f:
            f.write(netscape_content)
        return jsonify({"success": True, "path": DEFAULT_WORKSPACE_COOKIE_PATH})
    except Exception as e:
        return jsonify({"error": f"Failed to save cookie file: {str(e)}"}), 500

if __name__ == "__main__":
    # Standard development server on port 3000 to match AI Studio mapping
    port = int(os.environ.get("PORT", 8000))
    print(f"\n[SERVER RUNNING] Starting Flask application on http://0.0.0.0:{port}")
    print(f"Working local cookies.txt target path: {DEFAULT_WORKSPACE_COOKIE_PATH}\n")
    app.run(host="0.0.0.0", port=port, debug=True)
